NUMPY


In [6]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])


#Phần tử với index 2 và 4


In [ ]:
x[2], x[4]

In [7]:
data = [[1,2],[3,4],[5,6]]
mang = np.array(data)
print(mang)


[[1 2]
 [3 4]
 [5 6]]


In [68]:
mang[0,1]

np.int64(2)

In [9]:
mang[-1,1]

np.int64(6)

#Lấy 3 4 5 6 

In [11]:
mang[1:3]
mang[1:,:]
mang[1:]
mang[[1,2],]

array([[3, 4],
       [5, 6]])

In [29]:
mang[1:3]

array([[3, 4],
       [5, 6]])

# lấy 1 3 5

In [39]:
mang[:,0]

array([1, 5])

In [40]:
mang[[0,2],0]

array([1, 5])

# lấy 1 và 5 theo fomat start:end:step

In [42]:
mang[::2,0]

array([1, 5])

In [78]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
X=np.array(x)

lấy 2 6 10 14
lấy 7 11 
lấy 4 7 10

In [79]:
X[:,1]

array([ 2,  6, 10, 14])

In [80]:
X[1:3,2]

array([ 7, 11])

In [82]:
X[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

lấy 16 15 14 13

In [84]:
X[3,::-1]
X[- 1, -1::-1]

array([16, 15, 14, 13])

In [85]:
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
X=np.array(x)

lấy 4 5 6
lấy 2 5 
lấy 3 4
lấy 9 6 3 

In [107]:
X[1,:]

array([4, 5, 6])

In [89]:
X[:2,1]

array([2, 5])

In [108]:
X[[0,1],[2,0]]

array([3, 4])

In [109]:
X[::-1, 2]

array([9, 6, 3])

In [111]:
x = [1,2,3,4,5,6,7,8,9,10]
mang_chan = [ num for num in x if num % 2 == 0]
print(mang_chan)

[2, 4, 6, 8, 10]


In [112]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
np.arange(3)

array([0, 1, 2])

In [118]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [123]:
x = np.arange(3)
x

array([0, 1, 2])

In [124]:
x.shape

(3,)

In [126]:
x = x.reshape((3,1))
x

array([[0],
       [1],
       [2]])

In [154]:
y = np.arange(3)
x+y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6]])

In [155]:
#BÀI TẬP KẾT NUMPY
#Tạo một mảng numpy có kích thước 150 x 5.Hãy tưởng tượng mảng này chứa 150 mẫu về chiều cao, cân nặng, tuổi, lương, GPA của sinh viên VLU.
data = np.random.uniform(0,10,(150,5))
data.shape

(150, 5)

In [156]:
#Chia mảng bốn cột đầu tiên thành một biến có tên X và cột cuối cùng thành y
x = data[:,:-1]
y = data[:,-1]
x.shape, y.shape

((150, 4), (150,))

In [157]:
#Chia X thành X_train và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu.
dataset_size = x.shape[0]
dataset_size

150

In [158]:
train_size = int(0.7 * dataset_size)
train_size

105

In [159]:
x_train = x[:train_size]
x_test = x[train_size:]
x_train.shape , x_test.shape

((105, 4), (45, 4))

In [160]:
#Tạo 10 tập dữ liệu không chồng chéo của x_train
split = x_train.shape[0]//10
split

10

In [ ]:
for counter in range(0, x_train.shape[0], split):
    print(x_train[counter:counter+split].shape)

NameError: name 'x_train' is not defined

In [ ]:
#Nhận xét input output